name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend (no push)
        uses: docker/build-push-action@v6
        with:
          context: users_app
          file: users_app/backend/Dockerfile
          push: false
          tags: ${{ github.repository }}-backend:ci,${{ github.repository }}-backend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend (no push)
        uses: docker/build-push-action@v6
        with:
          context: users_app
          file: users_app/frontend/Dockerfile
          push: false
          tags: ${{ github.repository }}-frontend:ci,${{ github.repository }}-frontend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ui_tests_pw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ui_tests_pw (no push)
        uses: docker/build-push-action@v6
        with:
          context: ui_tests_pw
          file: ui_tests_pw/Dockerfile
          push: false
          tags: ${{ github.repository }}-frontend:ci,${{ github.repository }}-frontend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build api_tests (no push)
        uses: docker/build-push-action@v6
        with:
          context: api_tests
          file: api_tests/Dockerfile
          push: false
          tags: ${{ github.repository }}-frontend:ci,${{ github.repository }}-frontend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
